# TODO: redefine these
LOBBY_SCHEME = 'http://'
LOBBY_DOMAIN_NAME = '0.0.0.0'
LOBBY_PORT = 7231
LOBBY_URL = LOBBY_SCHEME + LOBBY_DOMAIN_NAME + ':' + str(LOBBY_PORT)

GAME_SERVER_SCHEME = 'http://'
GAME_SERVER_DOMAIN_NAME = '0.0.0.0'
GAME_SERVER_PORT = 8001
GAME_SERVER_URL = GAME_SERVER_SCHEME + GAME_SERVER_DOMAIN_NAME + ':' + str(GAME_SERVER_PORT)

STATUS_ERROR = "ERROR"
STATUS_OK = "OK"
