# TODO: redefine these
LOBBY_SCHEME = 'http://'
LOBBY_DOMAIN_NAME = '0.0.0.0'
LOBBY_PORT = 7231
LOBBY_URL = LOBBY_SCHEME + LOBBY_DOMAIN_NAME + ':' + str(LOBBY_PORT)

STATUS_ERROR = "ERROR"
STATUS_OK = "OK"
