apiVersion: v1
kind: Service
metadata:
  name: game-server-service
spec:
  type: NodePort
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: nodePort
