apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
spec:
  selector:
    matchLabels:
      app: game-server
  replicas: 1
  template:
    metadata:
      labels:
        app: game-server
        port: port
    spec:
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: game-server
        image: leargh/devxdev:latest
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"] 
        args: ["python3 /opt/devxdev/src/game_server_handler.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
