apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
spec:
  selector:
    matchLabels:
      app: lobby
  replicas: 1
  template:
    metadata:
      labels:
        app: lobby
    spec:
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: lobby
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        image: leargh/devxdev:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: ["python3 /opt/devxdev/src/lobby_handler.py --address 18.156.174.32 --port 7231"]
        securityContext:
          privileged: true